// <auto-generated />
namespace EvalMapping.ORM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.3.0")]
    public sealed partial class hp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(hp));
        
        string IMigrationMetadata.Id
        {
            get { return "201911140941322_hp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
